### ISSUE TITLE
Calling other functions doesn't work

### ISSUE THREAD

**Issue by asxlvm** [Arthurdw/dogehouse.py#10]
Hey, not sure if this is my issue, but this didn't return an error in discord.py's variant, look;

```py
  async def owner_check(authorid):
    ownerid = "de27447e-a633-484d-afaa-8377887dda7b"
    if authorid == ownerid:
      return True
    if authorid != ownerid:
      return False

  @command
  async def reboot(self, ctx: Message):
    await owner_check(authorid = ctx.author.id)
    if owner_check == True:
      await self.send("Rebooting the bot, I'll be back in 5 seconds!")
      await self.close()
      await asyncio.sleep(4)
      Client(DOGEHOUSE_TOKEN, DOGEHOUSE_REFRESH_TOKEN, prefix="d!", reconnect_voice=True).run()
      await asyncio.sleep(1)
      await self.send("I'm back online")
    else:
      return await self.send(f"{ctx.author.mention} You are not the owner of the bot so you may not reboot it!")
```

Error: `NameError: name 'owner_check' is not defined`

**Comment by Arthurdw** [comment]
Hey there.
First of all, this is not a library error, as you can see you are not assigning an `owner_check`  variable, you have created a function with that name. Second of all rebooting the client like that will not work and is not recommended as the client runs in an async loop, so your whole code will not work.

You are saying that discord.py's variant did not return an error, which would strongly surprise me as it is like I said earlier a mistake in your python code.

Also, a little note, in your `owner_check ` function, an `if` statement requires a boolean. And you created one, so why not return that as result instead of returning the True value manually. Also, in an `if` statement if a value is a boolean you should not check it, just place the boolean in the if statement. ^^
